name: Deploy to AWS App Runner

on:
  push:
    branches:
      - master  # Configura para que se ejecute en cada push a la rama 'main'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Cambia por la región que uses en AWS

      - name: Set up secrets for App Runner
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          # Guardar el secreto en un archivo para usarlo en App Runner
          echo "$SERVICE_ACCOUNT_KEY" > src/config/serviceAccountKey.json

      - name: Deploy to AWS App Runner
        run: |
          # Ejecutar el despliegue usando apprunner.yaml
          aws apprunner create-service --cli-input-yaml file://apprunner.yaml
