name: Deploy to AWS App Runner

on:
  push:
    branches:
      - master  # Configura para que se ejecute en cada push a la rama 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Cambia por la región que uses en AWS

      - name: Set up secrets for App Runner
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          # Guardar el secreto en un archivo para usarlo en App Runner da
          echo "$SERVICE_ACCOUNT_KEY" > src/config/serviceAccountKey.json
      - name: List files in src/config
        run: |
          echo "Listing files in src/config:"
          ls -l src/config
      - name: Validate serviceAccountKey.json content
        run: |
          echo "Content of serviceAccountKey.json:"
          cat src/config/serviceAccountKey.json | jq
      - name: Deploy to AWS App Runner
        run: |
          aws apprunner start-deployment --service-arn arn:aws:apprunner:us-east-2:891377194889:service/client-gateway/66409566b55845b88cc43581ed84a863

